const fs = require("fs-extra");
const path = require("path");
const os = require("os");
const simpleGit = require("simple-git");
const axios = require("axios");
const { v4: uuidv4 } = require("uuid");

const GITHUB_API = "https://api.github.com";

/**
 * Create a new GitHub repository under the authenticated user's account.
 * Returns the clone URL (HTTPS).
 */
async function createGithubRepo(repoName) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN is not configured");

  const res = await axios.post(
    `${GITHUB_API}/user/repos`,
    {
      name: repoName,
      private: false,
      description: "Website generated by WebGen AI",
    },
    {
      headers: {
        Authorization: `token ${token}`,
        Accept: "application/vnd.github+json",
      },
    }
  );

  return res.data.clone_url;
}

/**
 * Generate deployment helper files (Dockerfile + README) in the export directory.
 */
function generateDeploymentFiles(dir, repoName) {
  fs.writeFileSync(
    path.join(dir, "Dockerfile"),
    `FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80`
  );

  fs.writeFileSync(
    path.join(dir, "README.md"),
    `# ${repoName}

> Website generated by **WebGen AI** (Llama + Gemini)

## Quick Start

Open \`index.html\` in your browser to preview the site.

## Docker Deployment

\`\`\`bash
docker build -t ${repoName} .
docker run -p 8080:80 ${repoName}
\`\`\`

Then visit [http://localhost:8080](http://localhost:8080).
`
  );
}

/**
 * Export a generated project to GitHub.
 *
 * @param {string} repoName   - Name for the new GitHub repo
 * @param {string} projectName - Name of the generated project (folder in generated-projects/)
 * @returns {string} The URL of the newly created GitHub repo
 */
async function exportProject(repoName, projectName) {
  const exportId = uuidv4();
  // Use OS temp directory for cross-platform compatibility (Windows + Linux)
  const dir = path.join(os.tmpdir(), `webgen_export_${exportId}`);

  await fs.ensureDir(dir);

  try {
    // 1. Copy the ACTUAL generated project files
    const projectRoot = path.join(__dirname, "../../generated-projects", projectName);
    const frontendDir = path.join(projectRoot, "frontend");

    if (!fs.existsSync(frontendDir)) {
      throw new Error(`Project "${projectName}" not found or has no frontend files`);
    }

    // Copy all frontend files (index.html, assets, etc.)
    await fs.copy(frontendDir, dir);

    // If the project has a backend, copy it too
    const backendDir = path.join(projectRoot, "backend");
    if (fs.existsSync(backendDir)) {
      await fs.copy(backendDir, path.join(dir, "backend"));
    }

    // Copy plan.json for reference
    const planFile = path.join(projectRoot, "plan.json");
    if (fs.existsSync(planFile)) {
      await fs.copy(planFile, path.join(dir, "plan.json"));
    }

    // 2. Generate deployment helper files
    generateDeploymentFiles(dir, repoName);

    // 3. Create the GitHub repo
    const repoUrl = await createGithubRepo(repoName);

    // 4. Build an authenticated remote URL so git push works without prompts
    //    Converts https://github.com/user/repo.git → https://<token>@github.com/user/repo.git
    const token = process.env.GITHUB_TOKEN;
    const authedUrl = repoUrl.replace("https://", `https://${token}@`);

    // 5. Git init, commit, and push
    const git = simpleGit(dir);

    await git.init();
    await git.add(".");
    await git.commit("Initial commit — exported from WebGen AI");
    await git.addRemote("origin", authedUrl);
    await git.branch(["-M", "main"]);
    await git.push("origin", "main");

    console.log(`✅ Exported "${projectName}" to GitHub: ${repoUrl}`);

    return repoUrl;
  } finally {
    // 6. Always clean up temp directory
    await fs.remove(dir).catch(() => {});
  }
}

module.exports = { exportProject };
