# Generated by Django 5.2 on 2025-12-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_voice_mood_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mode',
            field=models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional')], default='personal', max_length=20),
        ),
    ]
