# Generated by Django 5.2 on 2026-02-04 03:43

from django.db import migrations, models


def update_angry_to_sad(apps, schema_editor):
    """Convert all 'angry' mood entries to 'sad' in existing data."""
    JournalEntry = apps.get_model('dashboard', 'JournalEntry')
    JournalEntry.objects.filter(mood='angry').update(mood='sad')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userprofile'),
    ]

    operations = [
        migrations.RunPython(update_angry_to_sad, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('optimistic', 'Optimistic'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious')], default='neutral', max_length=20),
        ),
    ]
