# Generated by Django 5.2 on 2026-02-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_change_angry_to_sad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_names',
            field=models.TextField(blank=True, help_text='Comma-separated list of names for better voice recognition'),
        ),
    ]
