# Generated by Django 5.2 on 2026-02-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userprofile_custom_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('optimistic', 'Optimistic'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious')], default='neutral', max_length=20),
        ),
    ]
