# Generated by Django 6.0.2 on 2026-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0003_seed_ceo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('x_position', models.FloatField(help_text='Relative X position (0.0 to 1.0)')),
                ('y_position', models.FloatField(help_text='Relative Y position (0.0 to 1.0)')),
            ],
            options={
                'db_table': 'beacon_nodes',
            },
        ),
    ]
