# Generated by Django 6.0.2 on 2026-03-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0004_beaconnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='#33B5E5', max_length=20)),
                ('x_min', models.FloatField(help_text='Min X percentage (0.0 to 1.0)')),
                ('y_min', models.FloatField(help_text='Min Y percentage (0.0 to 1.0)')),
                ('x_max', models.FloatField(help_text='Max X percentage (0.0 to 1.0)')),
                ('y_max', models.FloatField(help_text='Max Y percentage (0.0 to 1.0)')),
            ],
            options={
                'db_table': 'store_zones',
            },
        ),
    ]
