# Generated by Django 6.0.2 on 2026-03-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0005_storezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_plan_image_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'store_config',
            },
        ),
    ]
