# Generated by Django 6.0.2 on 2026-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0006_storeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_uuid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('x_position', models.FloatField(default=0.0)),
                ('y_position', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cart_locations',
            },
        ),
    ]
