# Generated by Django 6.0.2 on 2026-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0007_cartlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlocation',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storezone',
            name='zone_type',
            field=models.CharField(choices=[('aisle', 'Aisle'), ('boundary', 'Boundary'), ('obstacle', 'Obstacle')], default='aisle', max_length=20),
        ),
    ]
