# Generated by Django 6.0.2 on 2026-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0008_cartlocation_last_seen_storezone_zone_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeaconNode',
        ),
        migrations.AddField(
            model_name='storezone',
            name='major',
            field=models.IntegerField(blank=True, help_text='iBeacon major value', null=True),
        ),
        migrations.AddField(
            model_name='storezone',
            name='minor',
            field=models.IntegerField(blank=True, help_text='iBeacon minor value', null=True),
        ),
    ]
