# Generated by Django 6.0.2 on 2026-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0009_delete_beaconnode_storezone_major_storezone_minor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField(help_text='Start X percentage (0.0 to 1.0)')),
                ('start_y', models.FloatField(help_text='Start Y percentage (0.0 to 1.0)')),
                ('end_x', models.FloatField(help_text='End X percentage (0.0 to 1.0)')),
                ('end_y', models.FloatField(help_text='End Y percentage (0.0 to 1.0)')),
                ('length', models.FloatField(default=0.0, editable=False, help_text='Euclidean distance between the two endpoints')),
            ],
            options={
                'db_table': 'route_paths',
            },
        ),
    ]
